In [36]:
# read data
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('potential_loc.csv')

In [37]:
df

       latitude  longitude
0     42.325772 -73.773566
1     41.281236 -73.546263
2     42.889565 -78.008560
3     44.483723 -73.536897
4     42.965519 -77.626898
...         ...        ...
9995  42.566149 -78.758366
9996  42.311179 -75.867360
9997  43.764807 -73.454978
9998  42.744821 -78.101987
9999  44.156458 -76.044516

[10000 rows x 2 columns]

In [38]:
data = pd.read_csv(f'../child_care_regulated/child_care_regulated.csv')
data['lat_lon'] = data[['latitude', 'longitude']].values.tolist()

data['zip_code'] = data['zip_code'].astype(str)

for i in range(len(data)):
    if len(data['zip_code'][i]) < 5:
        data.loc[i, 'zip_code'] = '0' * (5 - len(data['zip_code'][i])) + data['zip_code'][i]
    if len(data['zip_code'][i]) == 9:
        data.loc[i, 'zip_code'] = data['zip_code'][i][:5]

full_list_of_current_facilities = data['lat_lon'].tolist()
corresponding_zip_codes = data['zip_code'].astype(str).tolist()

In [39]:
df

       latitude  longitude
0     42.325772 -73.773566
1     41.281236 -73.546263
2     42.889565 -78.008560
3     44.483723 -73.536897
4     42.965519 -77.626898
...         ...        ...
9995  42.566149 -78.758366
9996  42.311179 -75.867360
9997  43.764807 -73.454978
9998  42.744821 -78.101987
9999  44.156458 -76.044516

[10000 rows x 2 columns]

In [40]:
def most_frequent(List):
    return max(set(List), key=List.count)

zip_codes = []
for i in range(len(df)):
    adjacent_facilities = []
    for j in range(len(full_list_of_current_facilities)): 
        if np.linalg.norm(np.array(df.iloc[i]) - np.array(full_list_of_current_facilities[j])) < 0.1: 
            adjacent_facilities.append(corresponding_zip_codes[j])

    zip_codes.append(most_frequent(adjacent_facilities))

    if i % 100 == 0:
        print(i)

df["zip_code"] = zip_codes

0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900

ValueError: Length of values (50000) does not match length of index (10000)

In [42]:
zip_codes

['1',
 '2',
 '5',
 '3',
 '4',
 '1',
 '0',
 '5',
 '9',
 '0',
 '1',
 '4',
 '5',
 '2',
 '5',
 '1',
 '2',
 '9',
 '4',
 '4',
 '1',
 '4',
 '4',
 '6',
 '7',
 '1',
 '2',
 '0',
 '1',
 '0',
 '1',
 '4',
 '8',
 '7',
 '9',
 '1',
 '0',
 '9',
 '7',
 '7',
 '1',
 '0',
 '9',
 '8',
 '0',
 '1',
 '1',
 '5',
 '5',
 '0',
 '1',
 '2',
 '9',
 '8',
 '5',
 '1',
 '0',
 '9',
 '5',
 '0',
 '1',
 '3',
 '3',
 '6',
 '7',
 '1',
 '1',
 '9',
 '0',
 '1',
 '1',
 '4',
 '7',
 '0',
 '6',
 '1',
 '4',
 '8',
 '8',
 '6',
 '1',
 '4',
 '8',
 '1',
 '0',
 '1',
 '4',
 '5',
 '2',
 '7',
 '1',
 '2',
 '5',
 '4',
 '5',
 '1',
 '2',
 '3',
 '0',
 '3',
 '1',
 '3',
 '0',
 '2',
 '1',
 '1',
 '3',
 '0',
 '3',
 '7',
 '1',
 '2',
 '4',
 '1',
 '4',
 '1',
 '2',
 '8',
 '0',
 '4',
 '1',
 '4',
 '0',
 '6',
 '3',
 '1',
 '4',
 '4',
 '5',
 '6',
 '1',
 '2',
 '0',
 '1',
 '0',
 '1',
 '1',
 '9',
 '3',
 '4',
 '1',
 '3',
 '1',
 '1',
 '6',
 '1',
 '4',
 '7',
 '3',
 '9',
 '1',
 '2',
 '9',
 '2',
 '1',
 '1',
 '4',
 '0',
 '2',
 '0',
 '1',
 '4',
 '8',
 '2',
 '3',
 '1',
 '2',
 '0',
 '5',
 '3',
 '1',
 '4',
 '0',
 '1',
 '1',
 '1',
 '0',
 '5',
 '9',
 '0',
 '1',
 '3',
 '6',
 '3',
 '4',
 '1',
 '1',
 '9',
 '6',
 '8',
 '1',
 '4',
 '5',
 '2',
 '5',
 '1',
 '0',
 '5',
 '6',
 '2',
 '1',
 '3',
 '1',
 '4',
 '5',
 '1',
 '2',
 '1',
 '8',
 '2',
 '1',
 '3',
 '4',
 '8',
 '0',
 '1',
 '2',
 '4',
 '1',
 '3',
 '1',
 '4',
 '6',
 '2',
 '1',
 '1',
 '4',
 '4',
 '1',
 '1',
 '1',
 '2',
 '7',
 '9',
 '1',
 '1',
 '4',
 '8',
 '1',
 '0',
 '1',
 '4',
 '4',
 '8',
 '7',
 '1',
 '4',
 '8',
 '9',
 '5',
 '1',
 '4',
 '8',
 '1',
 '0',
 '1',
 '4',
 '0',
 '0',
 '6',
 '1',
 '2',
 '9',
 '6',
 '2',
 '1',
 '3',
 '1',
 '2',
 '6',
 '1',
 '3',
 '3',
 '6',
 '5',
 '1',
 '4',
 '0',
 '6',
 '3',
 '1',
 '4',
 '8',
 '7',
 '3',
 '1',
 '4',
 '5',
 '1',
 '0',
 '1',
 '1',
 '7',
 '5',
 '7',
 '1',
 '2',
 '1',
 '8',
 '0',
 '1',
 '2',
 '1',
 '8',
 '4',
 '1',
 '2',
 '0',
 '8',
 '6',
 '1',
 '3',
 '4',
 '2',
 '1',
 '1',
 '3',
 '8',
 '2',
 '0',
 '1',
 '3',
 '6',
 '1',
 '7',
 '1',
 '2',
 '0',
 '5',
 '6',
 '1',
 '2',
 '0',
 '1',
 '0',
 '1',
 '4',
 '4',
 '5',
 '0',
 '1',
 '3',
 '8',
 '2',
 '0',
 '1',
 '3',
 '6',
 '6',
 '9',
 '1',
 '0',
 '5',
 '4',
 '9',
 '1',
 '2',
 '9',
 '1',
 '2',
 '1',
 '3',
 '1',
 '1',
 '4',
 '1',
 '3',
 '1',
 '4',
 '5',
 '1',
 '2',
 '9',
 '3',
 '7',
 '1',
 '2',
 '9',
 '3',
 '5',
 '1',
 '3',
 '6',
 '0',
 '8',
 '1',
 '2',
 '0',
 '1',
 '0',
 '1',
 '2',
 '0',
 '1',
 '0',
 '1',
 '0',
 '5',
 '4',
 '7',
 '1',
 '4',
 '0',
 '8',
 '5',
 '1',
 '2',
 '9',
 '3',
 '5',
 '1',
 '3',
 '1',
 '2',
 '6',
 '1',
 '3',
 '0',
 '6',
 '9',
 '1',
 '3',
 '0',
 '3',
 '6',
 '1',
 '3',
 '7',
 '5',
 '3',
 '1',
 '4',
 '0',
 '8',
 '1',
 '1',
 '2',
 '7',
 '0',
 '1',
 '1',
 '4',
 '0',
 '7',
 '5',
 '1',
 '2',
 '9',
 '5',
 '3',
 '1',
 '4',
 '8',
 '9',
 '1',
 '1',
 '3',
 '4',
 '3',
 '1',
 '1',
 '2',
 '0',
 '2',
 '0',
 '1',
 '4',
 '8',
 '3',
 '0',
 '1',
 '3',
 '5',
 '0',
 '1',
 '1',
 '1',
 '7',
 '7',
 '9',
 '1',
 '2',
 '9',
 '3',
 '7',
 '1',
 '3',
 '6',
 '3',
 '4',
 '1',
 '2',
 '8',
 '0',
 '4',
 '1',
 '4',
 '6',
 '2',
 '3',
 '1',
 '2',
 '4',
 '8',
 '4',
 '1',
 '2',
 '5',
 '4',
 '9',
 '1',
 '2',
 '5',
 '4',
 '0',
 '1',
 '3',
 '1',
 '4',
 '8',
 '1',
 '1',
 '5',
 '2',
 '0',
 '1',
 '4',
 '0',
 '2',
 '0',
 '1',
 '2',
 '9',
 '8',
 '5',
 '1',
 '3',
 '7',
 '9',
 '0',
 '1',
 '0',
 '9',
 '4',
 '0',
 '1',
 '2',
 '8',
 '1',
 '6',
 '1',
 '0',
 '9',
 '6',
 '3',
 '1',
 '3',
 '7',
 '5',
 '3',
 '1',
 '3',
 '4',
 '4',
 '0',
 '1',
 '2',
 '0',
 '1',
 '8',
 '1',
 '2',
 '8',
 '2',
 '2',
 '1',
 '3',
 '0',
 '3',
 '1',
 '1',
 '3',
 '6',
 '6',
 '9',
 '1',
 '3',
 '8',
 '5',
 '6',
 '1',
 '4',
 '8',
 '9',
 '2',
 '1',
 '2',
 '0',
 '1',
 '8',
 '1',
 '2',
 '5',
 '0',
 '1',
 '1',
 '2',
 '5',
 '4',
 '9',
 '1',
 '1',
 '9',
 '6',
 '7',
 '1',
 '3',
 '0',
 '3',
 '5',
 '1',
 '4',
 '8',
 '4',
 '5',
 '1',
 '3',
 '7',
 '5',
 '3',
 '1',
 '3',
 '8',
 '4',
 '2',
 '1',
 '2',
 '3',
 '0',
 '3',
 '1',
 '4',
 '4',
 '8',
 '7',
 '1',
 '0',
 '9',
 '4',
 '1',
 '1',
 '2',
 '8',
 '3',
 '1',
 '1',
 '3',
 '6',
 '6',
 '9',
 '1',
 '0',
 '5',
 '9',
 '1',
 '1',
 '1',
 '7',
 '3',
 '3',
 '1',
 '3',
 '8',
 '2',
 '0',
 '1',
 '1',
 '7',
 '4',
 '6',
 '1',
 '4',
 '7',
 '1',
 '6',
 '1',
 '3',
 '6',
 '2',
 '0',
 '1',
 '3',
 '1',
 '2',
 '6',
 '1',
 '3',
 '3',
 '1',
 '5',
 '1',
 '0',
 '9',
 '2',
 '5',
 '1',
 '4',
 '0',
 '4',
 '8',
 '1',
 '4',
 '6',
 '2',
 '1',
 '1',
 '2',
 '8',
 '8',
 '3',
 '1',
 '3',
 '7',
 '5',
 '3',
 '1',
 '1',
 '9',
 '6',
 '7',
 '1',
 '4',
 '6',
 '2',
 '1',
 '1',
 '4',
 '5',
 '8',
 '0',
 '1',
 '2',
 '5',
 '9',
 '4',
 '1',
 '2',
 '1',
 '5',
 '7',
 '1',
 '2',
 '0',
 '9',
 '5',
 '1',
 '2',
 '0',
 '5',
 '3',
 '1',
 '4',
 '5',
 '2',
 '7',
 '1',
 '1',
 '7',
 '6',
 '3',
 '1',
 '4',
 '4',
 '7',
 '0',
 '1',
 '4',
 '3',
 '0',
 '5',
 '1',
 '2',
 '5',
 '6',
 '1',
 '1',
 '3',
 '8',
 '1',
 '5',
 '1',
 '0',
 '5',
 '6',
 '6',
 '1',
 '2',
 '5',
 '6',
 '6',
 '1',
 '3',
 '1',
 '1',
 '8',
 '1',
 '4',
 '8',
 '8',
 '3',
 '1',
 '4',
 '5',
 '1',
 '9',
 '1',
 '0',
 '9',
 '9',
 '0',
 '1',
 '2',
 '1',
 '8',
 '0',
 '1',
 '4',
 '4',
 '6',
 '9',
 '1',
 '2',
 '5',
 '0',
 '1',
 '1',
 '1',
 '2',
 '1',
 '9',
 '1',
 '4',
 '6',
 '2',
 '1',
 '1',
 '4',
 '8',
 '5',
 '0',
 '1',
 '1',
 '9',
 '3',
 '7',
 '1',
 '2',
 '9',
 '3',
 '7',
 '1',
 '4',
 '0',
 '7',
 '0',
 '1',
 '4',
 '6',
 '1',
 '1',
 '1',
 '3',
 '0',
 '3',
 '2',
 '1',
 '3',
 '7',
 '6',
 '0',
 '1',
 '4',
 '4',
 '3',
 '3',
 '1',
 '0',
 '9',
 '7',
 '7',
 '1',
 '3',
 '1',
 '2',
 '6',
 '1',
 '3',
 '3',
 '4',
 '6',
 '1',
 '2',
 '9',
 '8',
 '6',
 '1',
 '4',
 '8',
 '0',
 '4',
 '1',
 '2',
 '1',
 '1',
 '7',
 '1',
 '2',
 '4',
 '1',
 '4',
 '1',
 '2',
 '0',
 '7',
 '8',
 '1',
 '2',
 '5',
 '4',
 '0',
 '1',
 '0',
 '5',
 '6',
 '6',
 '1',
 '2',
 '9',
 '1',
 '2',
 '1',
 '3',
 '2',
 '0',
 '4',
 '1',
 '2',
 '9',
 '1',
 '6',
 '1',
 '4',
 '0',
 '0',
 '9',
 '1',
 '2',
 '0',
 '8',
 '3',
 '1',
 '2',
 '5',
 '0',
 '8',
 '1',
 '2',
 '0',
 '9',
 '5',
 '1',
 '2',
 '5',
 '4',
 '9',
 '1',
 '4',
 '7',
 '7',
 '9',
 '1',
 '2',
 '6',
 '0',
 '3',
 '1',
 '0',
 '5',
 '4',
 '1',
 '1',
 '4',
 '6',
 '2',
 '4',
 '1',
 '4',
 '0',
 '6',
 '3',
 ...]

In [43]:
zipcode_list = []
i = 0
zc = ''
while i < 50000:
    zc += zip_codes[i]

    if (i + 1) % 5 == 0:
        zipcode_list.append(zc)
        zc = ''

    i += 1

In [45]:
len(zipcode_list)

10000

In [46]:
df["zip_code"] = zipcode_list

In [47]:
# write to csv
df.to_csv('potential_loc_with_zip.csv', index=False)